[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.fmt]
description = "Format workspace members and excluded crates"
command = "sh"
args = [
  "-c",
  "cd .. && cargo fmt --all --manifest-path Cargo.toml && cargo fmt --manifest-path rln-wasm/Cargo.toml && cargo fmt --manifest-path rln-cli/Cargo.toml",
]

[tasks.fmt_check]
description = "Check formatting for workspace members and excluded crates"
command = "sh"
args = [
  "-c",
  "cd .. && cargo fmt --all --manifest-path Cargo.toml -- --check && cargo fmt --manifest-path rln-wasm/Cargo.toml -- --check && cargo fmt --manifest-path rln-cli/Cargo.toml -- --check",
]
