[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.fmt]
workspace = false
description = "Format all workspace members"
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--all"]

[tasks.fmt_check]
workspace = false
description = "Check formatting for all workspace members"
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]
