[package]
name = "rln-wasm"
version = "3.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[dependencies]
rand = { workspace = true }
zeroize = { workspace = true }
ark-groth16 = { workspace = true }
rand_chacha = { workspace = true }
ark-relations = { workspace = true }
rln = { path = "../rln", version = "3.0.0", default-features = false }
js-sys = "0.3.103"
wasm-bindgen = "0.2.126"
zerokit_utils = { path = "../utils", version = "3.0.0", default-features = false }
wasm-bindgen-rayon = { version = "1.3.0", features = [
    "no-bundler",
], optional = true }

# Logs panics via `console.error`, useful for debugging, but uses
# `std::fmt`/`std::panicking` and bloats code size (keep optional).
console_error_panic_hook = { version = "0.1.7", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.17", features = ["js"] }

[dev-dependencies]
ark-std = { workspace = true }
num-bigint = { workspace = true }
num-traits = { workspace = true }
wasm-bindgen-test = "0.3.76"
wasm-bindgen-futures = "0.4.76"

[dev-dependencies.web-sys]
version = "0.3.103"
features = ["Window", "Navigator"]

[features]
default = []
utils = []
panic_hook = ["console_error_panic_hook"]
parallel = ["rln/parallel", "wasm-bindgen-rayon", "ark-groth16/parallel"]

[package.metadata.docs.rs]
all-features = true
