[package]
name = "rln-cli"
version = "3.0.0"
edition = "2021"
publish = false

[[example]]
name = "relay"
path = "src/examples/relay.rs"

[[example]]
name = "stateless"
path = "src/examples/stateless.rs"

[[example]]
name = "multi_message_id"
path = "src/examples/multi_message_id.rs"

[[example]]
name = "poseidon2"
path = "src/examples/poseidon2.rs"

[[example]]
name = "partial"
path = "src/examples/partial.rs"

[dependencies]
rand = { workspace = true }
rln = { path = "../rln", version = "3.0.0", default-features = false }
clap = { version = "4.6.4", features = ["cargo", "derive", "env"] }
zerokit_utils = { path = "../utils", version = "3.0.0", default-features = false }

[features]
default = ["rln/parallel"]

[package.metadata.docs.rs]
all-features = true
