[package]
name = "zerokit_utils"
version = "3.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Various utilities for Zerokit"
documentation = "https://github.com/vacp2p/zerokit"
homepage = "https://vac.dev"
repository = "https://github.com/vacp2p/zerokit"

[lib]
bench = false
doctest = false

[dependencies]
rayon = { workspace = true }
ark-ff = { workspace = true }
zeroize = { workspace = true }
thiserror = { workspace = true }
num-bigint = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
ark-bn254 = { workspace = true }
criterion = { workspace = true }
num-traits = { workspace = true }
tiny-keccak = { workspace = true }
hex = "0.4.3"
hex-literal = "1.1.0"

[features]
default = []
parallel = ["ark-ff/parallel"]

[[bench]]
name = "merkle_tree_benchmark"
harness = false

[[bench]]
name = "poseidon_benchmark"
harness = false

[package.metadata.docs.rs]
all-features = true
