[package]
name = "rln"
version = "3.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "APIs to manage, compute and verify zkSNARK proofs and RLN primitives"
documentation = "https://github.com/vacp2p/zerokit"
homepage = "https://vac.dev"
repository = "https://github.com/vacp2p/zerokit"
exclude = ["resources/tree_depth_10/"]

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]
bench = false
doctest = false

[dependencies]
# ZKP Generation
ark-ec = { workspace = true }
ark-ff = { workspace = true }
ark-std = { workspace = true }
ark-poly = { workspace = true }
ark-bn254 = { workspace = true }
ark-groth16 = { workspace = true }
ark-relations = { workspace = true }
ark-serialize = { workspace = true }

# Error Handling
thiserror = { workspace = true }

# Utilities
rand = { workspace = true }
rayon = { workspace = true, optional = true }
zeroize = { workspace = true }
num-bigint = { workspace = true, features = ["std"] }
num-traits = { workspace = true }
rand_chacha = { workspace = true }
tiny-keccak = { workspace = true }
bon = "3.9"
ruint = { version = "1.20.0", default-features = false, features = [
    "rand",
    "serde",
    "ark-ff-05",
] }
tempfile = "3.27.0"
byteorder = "1.5.0"
zerokit_utils = { path = "../utils", version = "3.0.0", default-features = false }

# FFI
safer-ffi = "0.1.13"

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }
prost = "0.14.4"

# Non-WASM
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pmtree = { version = "3.0.1", package = "vacp2p_pmtree" }
sled = { version = "0.34.7", features = ["compression"] }

[dev-dependencies]
criterion = { workspace = true }
ark-crypto-primitives = { workspace = true, features = ["snark", "sponge"] }

[features]
default = ["parallel"]
parallel = [
    "rayon",
    "pmtree/parallel",
    "ark-ff/parallel",
    "ark-ec/parallel",
    "ark-std/parallel",
    "ark-poly/parallel",
    "ark-groth16/parallel",
    "ark-serialize/parallel",
    "zerokit_utils/parallel",
]
headers = ["safer-ffi/headers"] # Generate C header file with safer-ffi

[[bench]]
name = "generate_proof_benchmark"
harness = false

[[bench]]
name = "pm_tree_benchmark"
harness = false

[package.metadata.docs.rs]
all-features = true

[[bin]]
name = "generate_headers"
required-features = ["headers"] # Do not build unless generating headers.
