[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.test_default]
command = "cargo"
args = ["test", "--release", "--", "--nocapture"]

[tasks.test_stateless]
command = "cargo"
args = ["test", "--release", "--features", "stateless"]

[tasks.test_arkzkey]
command = "cargo"
args = ["test", "--release", "--features", "arkzkey"]

[tasks.bench]
command = "cargo"
args = ["bench"]
