[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.test]
command = "cargo"
args = ["test", "--release", "--", "--nocapture"]

[tasks.test_stateless]
command = "cargo"
args = [
	"test",
	"--release",
	"--no-default-features",
	"--features",
	"stateless",
	"--",
	"--nocapture",
]

[tasks.bench]
command = "cargo"
args = ["bench"]

[tasks.bench_icicle]
command = "cargo"
args = [
	"bench",
	"--bench",
	"proof_benchmark",
	"--no-default-features",
	"--features",
	"pmtree-ft,icicle",
]
