name: Add new issues and PRs to Vac Research project board

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Add to project board
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/orgs/vacp2p/projects/6
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
