on:
  workflow_run:
    workflows: ["Tests"]
    # branches: [master]
    types:
      - completed

name: Publish artifacts

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Update git submodules
        run: git submodule update --init --recursive
      - name: cargo build and ready artifacts
        run: |
            cargo build --release --workspace --exclude rln-wasm
            mkdir -p artifacts
            cp target/release/librln* artifacts/
            tar -cvzf zerokit-rln-artifacts-${{matrix.os}}.tar.gz ./artifacts/
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: zerokit-rln-artifacts-${{ matrix.os }}
          path: zerokit-rln-artifacts-${{matrix.os}}.tar.gz